### ISSUE TITLE
exp_test_ad fails exponential distributions if xmin>0

### ISSUE THREAD

**Issue by ProfessorPeregrine** [gagolews/agop#10]
I don't know if this was an issue in the original A-D test for exponentiality, but you can easily replicate this issue by generating exponential data, adding say 100 to it, and testing it.

One solution could be to have a parameter flag to subtract min() from the dataset to move it to zero for testing purposes.

Thank you for having this test in the package!

**Comment by gagolews** [comment]
Indeed, we are testing the non-shifted version (or shift=0) of this distribution here. This is in line with the pexp/dexp function from R's "base" library (stats).

Our assumption is that if a user wants to verify a hypothesis that a dataset follows a shifted distribution, they will un-shift it by themselves.

Still, thank you for this feature request.

**Comment by ProfessorPeregrine** [comment]
Yes, that is easy enough to do. Thanks again for putting the test in there!
